// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICore.Data;

namespace WebAPICore.Data.Migrations
{
    [DbContext(typeof(NextonContext))]
    partial class NextonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPICore.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<int?>("NextoneId");

                    b.HasKey("MissionId");

                    b.HasIndex("NextoneId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("WebAPICore.Models.Nextone", b =>
                {
                    b.Property<int>("NextoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpYears");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UrlImage");

                    b.HasKey("NextoneId");

                    b.ToTable("Nextones");
                });

            modelBuilder.Entity("WebAPICore.Models.Mission", b =>
                {
                    b.HasOne("WebAPICore.Models.Nextone")
                        .WithMany("Missions")
                        .HasForeignKey("NextoneId");
                });
#pragma warning restore 612, 618
        }
    }
}
